import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#8d004f',
        'on-error-container': '#93000a',
        'surface-variant': '#e2e2e2',
        'surface-container-highest': '#e2e2e2',
        'on-secondary': '#ffffff',
        'primary': '#000000',
        'on-secondary-container': '#efefff',
        'on-secondary-fixed-variant': '#0035be',
        'secondary': '#0040e0',
        'surface-container-high': '#e8e8e8',
        'surface-bright': '#f9f9f9',
        'tertiary-container': '#3e0020',
        'inverse-surface': '#303030',
        'inverse-primary': '#c6c6c6',
        'on-surface-variant': '#4c4546',
        'on-tertiary-container': '#f52991',
        'secondary-fixed': '#dde1ff',
        'on-error': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'background': '#f9f9f9',
        'primary-fixed': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#c6c6c6',
        'primary-container': '#1b1b1b',
        'outline-variant': '#cfc4c5',
        'tertiary': '#000000',
        'surface-dim': '#dadada',
        'on-background': '#1b1b1b',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#474747',
        'on-secondary-fixed': '#001356',
        'surface': '#f9f9f9',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#b8c3ff',
        'tertiary-fixed-dim': '#ffb0cb',
        'tertiary-fixed': '#ffd9e3',
        'surface-container': '#eeeeee',
        'on-primary-fixed': '#1b1b1b',
        'on-surface': '#1b1b1b',
        'inverse-on-surface': '#f1f1f1',
        'on-primary': '#ffffff',
        'surface-tint': '#5e5e5e',
        'error': '#ba1a1a',
        'outline': '#7e7576',
        'on-primary-container': '#848484',
        'on-tertiary-fixed': '#3e0020',
        'secondary-container': '#2e5bff',
        'toxic-green': '#00FF41',
        'hot-pink': '#FF007F',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'stack-lg': '32px',
        'margin-desktop': '48px',
        'border-width': '3px',
        'stack-sm': '8px',
        'shadow-offset': '6px',
        'margin-mobile': '16px',
        'stack-md': '16px',
      },
      fontFamily: {
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'display': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '1.0', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
        'code-sm': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'display': ['72px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' }],
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}

export default config
